syntax on
set number
set linebreak
set showbreak=+++
set textwidth=100
set showmatch
set colorcolumn=80
set hlsearch
set smartcase
set ignorecase
set incsearch
 
set autoindent
set shiftwidth=4
set smartindent
set expandtab
set softtabstop=4
 
set ruler

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END

set undolevels=1000
set backspace=indent,eol,start
